config/routes.rb
require 'domain_constraints'

Membership::Application.routes.draw do
  constraints(WebsiteDomain.new) do
    match '/' => 'website#index'
    match '/dashboard' => 'website#dashboard'
    match '/login' => 'sessions#new'
    match '/logout' => 'sessions#destroy'

    resources :courses, only: [:show]
    resources :events, only: [:show]
    resources :speakers, only: [:show]
  end

  constraints(ApplicationDomain.new) do
    match '/admin' => 'admin/admin#index'
    namespace :admin do
      match '/dashboard' => 'admin#dashboard'
      match '/login' => 'sessions#new'
      match '/logout' => 'sessions#destroy'

      resources :courses
      resources :events
      resources :sessions, only: [:create]
      resources :speakers
    end
  end

  root :to => 'errors#not_sure'
end

app/models/admin/event.rb
class Admin::Event < ::Event
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :date, :name, :publish, :speaker_ids

  has_many :events_speakers
  has_many :speakers, through: :events_speakers

  def to_s
    self.name
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController
  def index
    @q = Admin::Event.search(params[:q])
    @admin_events = @q.result(distinct: true).paginate(per_page: 20, page: params[:page])
  end

  def new
    @admin_event = Admin::Event.new
  end

  def create
    @admin_event = Admin::Event.new(params[:admin_event])

    if @admin_event.save
      redirect_to @admin_event, notice: 'Successfully created.'
    else
      render action: "new"
    end
  end

  def edit
    @admin_event = Admin::Event.find(params[:id])
  end

  def show
    @admin_event = Admin::Event.find(params[:id])
  end

  def update
    @admin_event = Admin::Event.find(params[:id])

    if @admin_event.update_attributes(params[:admin_event])
      redirect_to @admin_event, notice: 'Successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @admin_event = Admin::Event.find(params[:id])
    @admin_event.destroy
    redirect_to @admin_event, notice: 'Successfully deleted.'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
    @event = Event.find(params[:id])
  end
end

app/views/admin/events/_form.html.erb
<div class="row">
  <div class="large-12 columns">
    <%= form_for @admin_event do |f| %>
      <%= render 'shared/error_messages', target: @admin_event %>
      <div class="row">
        <div class="large-6 columns">
          <div class="row">
            <div class="large-12 columns">
              <%= f.label :name %>
              <%= f.text_field :name %>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="large-6 columns">
          <div class="row">
            <div class="large-12 columns">
              <%= f.label :speakers %>
              <%= hidden_field_tag "admin_event[speaker_ids][]", nil %>
              <% Admin::Speaker.all.each do |speaker| %>
                <%= check_box_tag "admin_event[speaker_ids][]", speaker.id, @admin_event.speaker_ids.include?(speaker.id), id: dom_id(speaker) %>
                <%= speaker %><br />
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <%= admin_form_actions(f, :admin, :events) %>
    <% end %>
  </div>
</div>

app/views/admin/events/_search.html.erb
<div id="myModal" class="reveal-modal">
  <div class="row admin_search_form">
    <div class="large-6 columns">
      <h2>Filter List</h2>
      <%= search_form_for @q do |f| %>
        <div class="row">
          <div class="large-12 columns">
            <%= f.label :name_cont %>
            <%= f.text_field :name_cont %>
          </div>
        </div>

        <%= admin_search_form_actions(f) %>
      <% end %>
    </div>
  </div>
  <a class="close-reveal-modal">x</a>
</div>

app/views/admin/events/edit.html.erb
<%- model_class = Admin::Event -%>
<%- provide(:title, t('event.title')) -%>
<%- provide(:navigation_highlight, 'tools') -%>

<%= render :partial => 'form' %>

app/views/admin/events/index.html.erb
<%- model_class = Admin::Event -%>
<%- provide(:title, t('event.title')) -%>
<%- provide(:navigation_highlight, 'tools') -%>

<div class="row">
  <div class="large-12 columns">
    <%= new_button(:admin, :event, :zurb) %>
    <%= render 'shared/filter' %>
    <%= render 'search' %>
    <%= will_paginate(@admin_events) %>

    <table>
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:name) %></th>
          <th><%= model_class.human_attribute_name(:created_at) %></th>
          <th><%=t '.actions', default: t('helpers.actions') %></th>
        </tr>
      </thead>
      <tbody>
        <% @admin_events.each do |event| %>
          <tr>
            <td><%= link_to event, admin_event_path(event) %></td>
            <td><%=l event.created_at, format: :created_at_date %></td>
            <td>
              <%= mini_edit_button(:admin, :event, event, :zurb) %>
              <%= mini_destroy_button(:admin, :event, event, :zurb) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/events/new.html.erb
<%- model_class = Admin::Event -%>
<%- provide(:title, t('event.title')) -%>
<%- provide(:navigation_highlight, 'tools') -%>

<%= render :partial => 'form' %>

app/views/admin/events/show.html.erb
<%- model_class = Admin::Event -%>
<%- provide(:title, t('.title')) -%>
<%- provide(:navigation_highlight, 'tools') -%>

<div class="row">
  <div class="large-12 columns">
    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:name) %></strong></dt>
      <dd><%= @admin_event %></dd>
    </dl>

    <h3>Speakers</h3>
    <ul>
      <% @admin_event.speakers.each do |speaker| %>
        <li><%= link_to speaker, admin_speaker_path(speaker) %></li>
      <% end %>
    </ul>

    <%= admin_show_actions(:admin, :event, :events, @admin_event) %>
  </div>
</div>