config/routes.rb
require 'domain_constraints'

Membership::Application.routes.draw do
  constraints(WebsiteDomain.new) do
    match '/' => 'website#index'
    match '/dashboard' => 'website#dashboard'
    match '/login' => 'sessions#new'
    match '/logout' => 'sessions#destroy'

    resources :courses, only: [:show]
    resources :events, only: [:show]
    resources :speakers, only: [:show]
  end

  constraints(ApplicationDomain.new) do
    match '/admin' => 'admin/admin#index'
    namespace :admin do
      match '/dashboard' => 'admin#dashboard'
      match '/login' => 'sessions#new'
      match '/logout' => 'sessions#destroy'

      resources :courses
      resources :events
      resources :sessions, only: [:create]
      resources :speakers
    end
  end

  root :to => 'errors#not_sure'
end

app/views/layouts/admin/_footer.html.erb
<%# if advertiser_current_user %>
  <section>
    <footer>
      <div class="row">
        <div class="large-6 columns">
        </div>
        <div id="builtby" class="large-6 columns">
        </div>
      </div>
    </footer>
  </section>
<%# end %>
<script>
  $(document).foundation();
</script>

app/views/layouts/admin/_header.html.erb
<%# if advertiser_current_user %>
  <section>
    <header>
      <nav class="top-bar">
        <ul class="title-area">
          <li class="name">
            <%= link_to 'Dashboard', admin_dashboard_path %>
          </li>
        </ul>

        <section class="top-bar-section">
          <ul class="right">
            <li class="divider"></li>
            <li class="has-dropdown not-click"><a href="#">Tools</a>
              <ul class="dropdown">
                <li><%= link_to "Courses", admin_courses_path %></li>
                <li><%= link_to "Events", admin_events_path %></li>
                <li><%= link_to "Speakers", admin_speakers_path %></li>
              </ul>
            </li>
            <li class="divider"></li>
            <li class="has-dropdown not-click"><a href="#">My Account</a>
              <ul class="dropdown">
                <li><%= link_to "Logout", admin_logout_path %></li>
              </ul>
            </li>
          </ul>
        </section>
      </nav>
    </header>
  </section>
<%# end %>

app/views/layouts/admin/index.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'admin', media: 'all' %>
    <%= yield :stylesheet_includes %>
    <%= javascript_include_tag 'admin' %>
    <%= yield :javascript_includes %>
    <%= csrf_meta_tags %>
    <%= render 'shared/shim' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/foundation/4.3.1/css/foundation.min.css" />
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/foundicons/2.0/stylesheets/general_foundicons.min.css" />
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/foundicons/2.0/stylesheets/accessibility_foundicons.min.css" />
    <script src="//cdn.jsdelivr.net/foundation/4.3.1/js/foundation.min.js"></script>
  </head>
  <body>
    <%= render 'shared/google_analytics' %>
    <section class="wrapper">
      <%= render 'layouts/admin/header' %>
      <%= render 'shared/flash_messages' %>
      <section id="admin" class="inner-wrapper">
        <section class="content">
          <%= yield %>
        </section>
      </section>
      <%= render 'layouts/admin/footer' %>
    </section>
  </body>
</html>