config/routes.rb
require 'domain_constraints'

Membership::Application.routes.draw do
  constraints(WebsiteDomain.new) do
    match '/' => 'website#index'
    match '/dashboard' => 'website#dashboard'
    match '/login' => 'sessions#new'
    match '/logout' => 'sessions#destroy'

    resources :courses, only: [:show]
    resources :events, only: [:show]
    resources :speakers, only: [:show]
  end

  constraints(ApplicationDomain.new) do
    match '/admin' => 'admin/admin#index'
    namespace :admin do
      match '/dashboard' => 'admin#dashboard'
      match '/login' => 'sessions#new'
      match '/logout' => 'sessions#destroy'

      resources :courses
      resources :events
      resources :sessions, only: [:create]
      resources :speakers
    end
  end

  root :to => 'errors#not_sure'
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
  layout :choose_layout

  def index
    @courses = Course.order(created_at: :DESC).all
    @events = Event.all
    @speakers = Speaker.all
  end

private
  def choose_layout
    'layouts/website/index'
  end
end

app/views/website/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Your Membership Website</h1>
  </div>
</div>

<div class="row">
  <div class="large-4 columns">
    <h3>Courses</h3>
    <ul>
      <% @courses.each do |course| %>
        <li><%= link_to course, course_path(course) %></li>
      <% end %>
    </ul>
  </div>
  <div class="large-4 columns">
    <h3>Events</h3>
    <ul>
      <% @events.each do |event| %>
        <li><%= link_to event, event_path(event) %></li>
      <% end %>
    </ul>
  </div>
  <div class="large-4 columns">
    <h3>Speakers</h3>
    <ul>
      <% @speakers.each do |speaker| %>
        <li><%= link_to speaker, speaker_path(speaker) %></li>
      <% end %>
    </ul>
  </div>
</div>